services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
    networks:
      - rabbitmq_network
    environment:
      RABBITMQ_HOST: rabbitmq
      
  db:
    image: mysql
    restart: always
    ports:
      - 9306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - rabbitmq_network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    external: true
   