services:
  rabbitmq:
    build: .
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"
      - "15674:15674"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    name: rabbitmq_network # Define o nome da rede que será criada
    driver: bridge